# Micronaut App Props
micronaut.application.name=boarding
micronaut.application.version=0.1

# Micronaut Server Props
micronaut.server.port=8080
micronaut.server.cors=true
micronaut.server.cors.configurations.ui.allowed-origins=*

# Dynamo DB Props
dynamodb.endpoint=http://localhost:8000
dynamodb.train-table-name=Train